### ISSUE TITLE
Add grand-fathering code for price change

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/custom-functions#17]
The price change goes into effect on March 1, 2021. In order to grand father existing customers into the old price, the following filter needs to be added before that date:

```php
/**
 * Set the price that customers pay prior to March 1, 2021 
 *
 * @param $price float The current item price
 * @param $download_id int Download product ID
 * @param $options array the cart item options
 * @return float
 */
function sc_edd_sl_grandfather( $price, $download_id, $options ) {


	if( ! empty( $options['license_id'] ) ) {

		// Only existing license keys get grandfathered

		$license = edd_software_licensing()->get_license( $options['license_id'] );

		if( $license && $license->date_created < '2021-03-01 00:00:00' ) {

			switch( $license->download_id ) {

				case 20 :

					$price = 89;
					break;

				case 19 :

					$price = 49;
					break;

				case 18 :

					$price = 29;
					break;

			}

		}

	}

	return $price;
}
add_filter( 'edd_cart_item_price', 'sc_edd_sl_grandfather', 10, 3 );
```

@SDavisMedia I've tested this locally and it should be all that's needed but please verify.

**Comment by SeanChDavis** [comment]
@pippinsplugins Okay I've been testing this for a bit now. It's fine for renewals but I think it's affecting upgrades in a way that we weren't planning.

In my dev environment I've already updated the download prices, and the above code is in place.  With a license upgrade in the cart, the price of that cart item (which is a license upgrade) is changing to the [filtered] price of the license _from which_ you are upgrading.

I feel like I'm seeing two issues. Let's say you previously purchased a **Personal** license for $29. That means you could (in the past) upgrade to **Plus** for $20 ($49 minus $29). Now put the above code in place and update the download prices to the new prices. After doing that, two things happen:

1. Your **Personal** to **Plus** upgrade display price (on the upgrades table) becomes $50 ($99 minus $49). This may be intentional. It's as if you've been given a credit for the difference between the old Personal price and the new Personal price. **Can you confirm this is expected?** If it is, then I only see one issue...

2. When you actually put the upgrade in the cart, **the upgrade price becomes $29** (it should be $50, or whatever is correct from the point above). It appears this is happening because of the filtered prices. It seems the upgrade price is being filtered based on the grandfathered price of the download associated with the license that is being upgraded. If I'm wrapping my head around this properly, I think we'd need to either exclude upgrades or specify renewals.

Thoughts?

**Comment by pippinsplugins** [comment]
That's not what we want.

Upgrades should still be priced based on what they _paid_, so a $29 purchase upgrading to a $99 (post increase) should be $70.

I'll work on it.

**Comment by pippinsplugins** [comment]
@SDavisMedia haven't tested it yet but I'm pretty sure all we need to is to change 
```php
if( ! empty( $options['license_id'] ) ) {
```
to
```php
if( ! empty( $options['license_id'] ) && empty( $options['upgrade_id'] ) ) {
```

The upgrade logic in SL already looks up the past purchase and uses the amount paid for the discount calculation, so there's no need to override that.

**Comment by SeanChDavis** [comment]
Just noting that I'm working on this. Point 2 above is taken care of with the change you suggested, checking to make sure it's not an upgrade before executing. Point 2 is unchanged, though. However, I'm trying to recreate the same scenario on AffiliateWP. I have a hunch we're doing the same thing over there after its price change late last year.

EDIT: I meant to say "Point 1 is unchanged, though."

**Comment by pippinsplugins** [comment]
Hmm, the price adjustment shouldn't happen when an upgrade is in the cart. Checking for the `upgrade_id` should be preventing that.

**Comment by SeanChDavis** [comment]
@pippinsplugins Sorry, my above comment should be "Point 2 above is taken care of with the change you suggested, checking to make sure it's not an upgrade before executing. Point 1 is unchanged, though."

So yes, the price adjustment is _not_ happening while an upgrade is in the cart. However, the following statement you made is not working as you described (and that's what I'm currently trying to test AWP site for):

"Upgrades should still be priced based on what they paid, so a $29 purchase upgrading to a $99 (post increase) should be $70."

That's not what's happening, and I'm pretty sure it's not happening on AWP site either. Are you 100% positive that's what's supposed to happen? Upgrade pricing seems to be based on current price of the item you're upgrading from, not the price you paid back when it was a lower price.

**Comment by SeanChDavis** [comment]
To be clear, I can still get this live now. The grandfathering is working as expected.

**Comment by pippinsplugins** [comment]
Yes that is definitely what we want to have happen.

In Software Licensing, the cost of an upgrade is determined by the amount previously paid so long as the `Pro-rate` check box is enabled in the License Upgrades on the product edit screen.

![image](https://user-images.githubusercontent.com/1034109/108746875-7d72ec00-7502-11eb-9014-2e115665872e.png)

I just reviewed the logic in SL and found why it's not working. We have this filter:
```php
/**
 * Allow using the previously paid amount as the $old_price
 *
 * Some store owners would prefer that the old price be based off what was previously paid, instead of what
 * the current price ID value is. Returning false here, allows the $old_price to be based on the last amount paid
 * instead of the current price of the Price ID, in the event it has been changed.
 *
 * @since 3.6.4
 *
 * @param bool             Should we use the current price of the Price ID for prorated estimates.
 * @param int  $license_id The License ID requesting the prorated cost.
 * @param int  $download_id The Download ID associated with the license.
 */
$use_current_price = apply_filters( 'edd_sl_use_current_price_proration', true, $license_id, $download_id );
```

Add `apply_filters( 'edd_sl_use_current_price_proration', '__return_false' )` and then it should work!

**Comment by pippinsplugins** [comment]
When `edd_sl_use_current_price_proration` comes back as `true`, it looks up the currently assigned price for the price option, rather than the amount that was paid.

**Comment by SeanChDavis** [comment]
@pippinsplugins Thank you much!! 🙌 I'll get this all implemented and tested shortly. If all is well, you won't hear from me again.

**Comment by SeanChDavis** [comment]
@pippinsplugins That filter is not going to work because it only applies to variable pricing. It's inside of a `$download->has_variable_prices()` conditional. SC uses completely separate downloads for the pricing tiers. Line 290 [in this code](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/e61c471ac9b547b7ad7936ef4e3802539621e115/includes/license-upgrades.php#L236-L292) is where the old price value is coming from. `$old_price = edd_get_download_price( $download_id );`

This puts SC and AWP in two completely different situations. For what it's worth, I recreated this price change/upgrade situation on AWP site and the aforementioned filter does what we expected because AWP price tiers are variable prices.

It looks like controlling what's used as the old price for a single price download either has to be done through some roundabout way, or there's no quick solution for this. SL bug/oversight?

I'm going to get the grandfather part in place, at least.

**Comment by pippinsplugins** [comment]
@SDavisMedia dang, you're totally right. I wonder how it's never come up before that our SL logic doesn't match between variable and non-variable prices . . . 

I'm going to work on fixing that.

**Comment by SeanChDavis** [comment]
Cool cool. Grandfather code is live. I'm going to close this issue since it's taken care of. Any further changes can come in a new issue here or a fix in SL.

**Comment by pippinsplugins** [comment]
SL issue created https://github.com/easydigitaldownloads/EDD-Software-Licensing/issues/1763
